spring:
  data:
    mongodb:
      uri: mongodb://101.132.120.236:27017/ACHD

  mvc:
    view:
      prefix: classpasth:/templates/
      suffix: .html

  thymeleaf:
    cache: false
server:
  port: 8090